apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: digital-hub-ui
        #todo the following needs to be parameterized instead of relying on the latest verions
          image:  gcr.io/dh-v1-216802/github-farhadkzm-dh:5764b7750f11c3b17489be36c84d6392b0e93a62
          imagePullPolicy: Always # latest version might change
          command: ["/bin/sh"]
          args: ["-c", "node /app/app.js"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: rest
    port: 80
    targetPort: 3000
  selector:
    app: {{ .Chart.Name }}
